name: dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  avatar_glow: ^3.0.1
  bloc: ^8.1.4
  bot_toast: ^4.1.3
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  shared_preferences: ^2.2.3
  flutter_localizations:
        sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
  uses-material-design: true
  assets:
    - assets/icons/home/
    - assets/icons/auth/
    - assets/icons/explore/
    - assets/icons/library/
    - assets/icons/profile/
    - assets/images/
flutter_intl:
  enabled: true
